version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build-api:
    executor: python/default
    working_directory: ~/backend/api
    steps:
      - checkout


      - python/install-packages:
          pkg-manager: pipenv

workflows:
  main:
    jobs:
      - build-api