version: 2

jobs:
  build:
    working_directory: ~/backend/api
    docker:
      - image: cimg/python:3.10.1  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

{% include 'build.yml' %}
