version: 2

parameters:
  service:
    type: string

jobs:
  build-api:
    when: << pipeline.parameters.service == 'api' >>
    working_directory: ~/backend/api
    docker:
      - image: cimg/python:3.10.1  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      {% include 'build.yml' %}
  
  always-build:
    working_directory: ~/backend/api
    docker:
      - image: cimg/python:3.10.1  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      {% include 'build.yml' %}
