version: 2.1

orbs:
  python: circleci/python@1.1.0
  node: circleci/node@5.0.0

jobs:
  {% for k in builds %}
  build-{{builds[k]['jobname']}}:
    executor: {{ builds[k]['executor'] }}
    working_directory: {{ builds[k]['working_directory'] }}
    steps:
      - checkout
      {% include builds[k]['filename'] %}
  {% endfor %}

workflows:
  main:
    jobs:
      {% for k in builds %}
      - build-{{builds[k]['jobname']}}
      {% endfor %}