version: 2.1

setup: true

orbs:
  python: circleci/python@2.0.1
  path-filtering: circleci/path-filtering@0.0.1

jobs:
  setup:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Generate config
          command: ./.circleci/generate-config.sh
  filter:
    executor: path-filtering/default
    steps:
      - path-filtering/filter:
          base-revision: main
          config-path: generated_config.yml
          mapping: |
            backend/api/.*       service    api
            backend/consumer/.*  service    consumer
            frontend/.*          service    frontend
            .*                   service    none
workflows:
  setup:
    jobs:
      - setup