version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  python: circleci/python@2.0.1

workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: generated_config.yml