version: 2.1

setup: true

orbs:
  helm: circleci/helm@1.2.0
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Generate config
          command: ./.circleci/generate-config.sh 
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup