version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  python: circleci/python@2.0.1

jobs:
  setup:
    executor: python/default
    parameters:
      base-revision:
        default: main
        description: |
            The revision to compare the current one against for the purpose of determining changed files.
        type: string
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install Jinja2
          command: pip install jinja2
      - run:
          name: Python command
          command: python ./.circleci/generate-config.py
      - run:
          name: check file
          command: cat generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup