version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  python: circleci/python@2.0.1

jobs:
  setup:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: ./circleci/generated_config.yml

workflows:
  setup:
    jobs:
      - setup